Watching for file changes with StatReloader
Главная страница была посещена.
"GET / HTTP/1.1" 200 951
"GET /static/my_dz_1/css/style.css HTTP/1.1" 200 609
"GET /static/my_dz_1/image/583.jpg HTTP/1.1" 200 2057688
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 1289
Главная страница была посещена.
"GET / HTTP/1.1" 200 951
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 1289
Главная страница была посещена.
"GET / HTTP/1.1" 200 951
Watching for file changes with StatReloader
Главная страница была посещена.
"GET / HTTP/1.1" 200 951
"GET /static/my_dz_1/css/style.css HTTP/1.1" 304 0
Главная страница была посещена.
"GET / HTTP/1.1" 200 951
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 1289
Главная страница была посещена.
"GET / HTTP/1.1" 200 951
Watching for file changes with StatReloader
Главная страница была посещена.
"GET / HTTP/1.1" 200 903
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 1211
Главная страница была посещена.
"GET / HTTP/1.1" 200 903
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 1211
Главная страница была посещена.
"GET / HTTP/1.1" 200 903
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 1211
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 1211
C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_1\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Главная страница была посещена.
"GET / HTTP/1.1" 200 903
Главная страница была посещена.
"GET / HTTP/1.1" 200 903
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 903
Главная страница была посещена.
"GET / HTTP/1.1" 200 903
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 903
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 903
Главная страница была посещена.
"GET / HTTP/1.1" 200 903
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 903
C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_1\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Главная страница была посещена.
"GET / HTTP/1.1" 200 903
"GET /static/my_dz_1/css/style.css HTTP/1.1" 304 0
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 1213
Главная страница была посещена.
"GET / HTTP/1.1" 200 903
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 1213
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Главная страница была посещена.
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_1\views.py", line 13, in index
    return render(request, 'my_dz_1/index.html', {'title': 'Главная страница'})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: my_dz_1/index.html
"GET / HTTP/1.1" 500 78889
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2442
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 10629
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2462
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2513
C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_2\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2261
"GET /client/2 HTTP/1.1" 301 0
Internal Server Error: /client/2/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_2\views.py", line 7, in client_detail
    client = Client.objects.get(pk=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
my_dz_2.models.Client.DoesNotExist: Client matching query does not exist.
"GET /client/2/ HTTP/1.1" 500 71682
Not Found: /client/<int:client_id 2
"GET /client/%3Cint:client_id%202 HTTP/1.1" 404 2358
Not Found: /client/client_id 2
"GET /client/client_id%202 HTTP/1.1" 404 2335
Not Found: /client/client_id
"GET /client/client_id HTTP/1.1" 404 2327
Not Found: /client/client_id
"GET /client/client_id?2 HTTP/1.1" 404 2329
Not Found: /client/
"GET /client/ HTTP/1.1" 404 2300
"GET /client/1 HTTP/1.1" 301 0
Internal Server Error: /client/1/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_2\views.py", line 9, in client_detail
    return render(request, 'client_detail.html', {'client': client, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: client_detail.html
"GET /client/1/ HTTP/1.1" 500 78733
Internal Server Error: /client/1/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_2\views.py", line 9, in client_detail
    return render(request, 'client_detail.html', {'client': client, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: client_detail.html
"GET /client/1/ HTTP/1.1" 500 78733
Internal Server Error: /client/1/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_2\views.py", line 9, in client_detail
    return render(request, 'client_detail.html', {'client': client, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: client_detail.html
"GET /client/1/ HTTP/1.1" 500 78870
Internal Server Error: /client/1/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_2\views.py", line 9, in client_detail
    return render(request, 'client_detail.html', {'client': client, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: client_detail.html
"GET /client/1/ HTTP/1.1" 500 78870
Internal Server Error: /client/1/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_2\views.py", line 9, in client_detail
    return render(request, 'client_detail.html', {'client': client, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: client_detail.html
"GET /client/1/ HTTP/1.1" 500 78870
C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /client/1/ HTTP/1.1" 200 540
Internal Server Error: /client/2/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_2\views.py", line 7, in client_detail
    client = Client.objects.get(pk=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
my_dz_2.models.Client.DoesNotExist: Client matching query does not exist.
"GET /client/2/ HTTP/1.1" 500 71690
"GET /client/3/ HTTP/1.1" 200 533
"GET /client/3/ HTTP/1.1" 200 615
"GET /static/my_dz_1/css/style.css HTTP/1.1" 404 1822
"GET /client/3/ HTTP/1.1" 200 615
"GET /static/my_dz_1/css/style.css HTTP/1.1" 404 1822
"GET /client/3/ HTTP/1.1" 200 615
"GET /static/my_dz_1/css/style.css HTTP/1.1" 404 1822
"GET /client/3/ HTTP/1.1" 200 615
"GET /static/my_dz_1/css/style.css HTTP/1.1" 404 1822
"GET /client/3/ HTTP/1.1" 200 615
"GET /static/my_dz_2/css/style.css HTTP/1.1" 200 609
"GET /client/3/ HTTP/1.1" 200 615
"GET /client/3/ HTTP/1.1" 200 664
"GET /client/3/ HTTP/1.1" 200 1610
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2261
Internal Server Error: /client/3/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_2\views.py", line 7, in client_detail
    client = Client.objects.get(pk=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
my_dz_2.models.Client.DoesNotExist: Client matching query does not exist.
"GET /client/3/ HTTP/1.1" 500 71708
Watching for file changes with StatReloader
"GET /client/1/ HTTP/1.1" 200 1213
Watching for file changes with StatReloader
"GET /client/1/ HTTP/1.1" 200 1616
"GET /client/2/ HTTP/1.1" 200 762
"GET /client/3/ HTTP/1.1" 200 761
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2261
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2312
"GET /client/3/ HTTP/1.1" 200 761
"GET /static/my_dz_2/css/style.css HTTP/1.1" 304 0
"GET /client/1/ HTTP/1.1" 200 1616
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2261
"GET /client/3/ HTTP/1.1" 200 761
"GET /static/my_dz_2/css/style.css HTTP/1.1" 304 0
"GET /client/1/ HTTP/1.1" 200 1616
C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_2\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /client/4/ HTTP/1.1" 200 760
C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients HTTP/1.1" 301 0
"GET /clients/ HTTP/1.1" 200 737
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 737
"GET /clients/ HTTP/1.1" 200 737
C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 690
"GET /clients/ HTTP/1.1" 200 690
"GET /client/4/ HTTP/1.1" 200 760
"GET /clients/ HTTP/1.1" 200 690
C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 737
"GET /clients/ HTTP/1.1" 200 737
"GET /clients/ HTTP/1.1" 200 796
"GET /client/2/ HTTP/1.1" 200 762
"GET /client/4/ HTTP/1.1" 200 760
"GET /client/4/ HTTP/1.1" 200 760
"GET /client/3/ HTTP/1.1" 200 761
"GET /client/4/ HTTP/1.1" 200 760
"GET /client/3/ HTTP/1.1" 200 761
"GET /client/2/ HTTP/1.1" 200 762
"GET /client/1/ HTTP/1.1" 200 1616
"GET /client/2/ HTTP/1.1" 200 762
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2436
"GET /client/3/ HTTP/1.1" 200 761
"GET /clients/ HTTP/1.1" 200 796
"GET /client/2/ HTTP/1.1" 200 762
"GET /client/1/ HTTP/1.1" 200 1616
"GET /client/4/ HTTP/1.1" 200 760
Not Found: /clients/3
"GET /clients/3 HTTP/1.1" 404 2481
"GET /client/3 HTTP/1.1" 301 0
"GET /client/3/ HTTP/1.1" 200 761
"GET /client/1/ HTTP/1.1" 200 1616
Not Found: /
"GET / HTTP/1.1" 404 2436
"GET /client/3/ HTTP/1.1" 200 761
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2436
"GET /client/3/ HTTP/1.1" 200 761
Not Found: /clints
"GET /clints HTTP/1.1" 404 2472
Not Found: /clint/1
"GET /clint/1 HTTP/1.1" 404 2475
"GET /client/1/ HTTP/1.1" 200 1616
"GET /clients/ HTTP/1.1" 200 796
"GET /client/3/ HTTP/1.1" 200 761
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2436
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2487
"GET /client/3/ HTTP/1.1" 200 761
"GET /client/1/ HTTP/1.1" 200 1616
"GET /clients/ HTTP/1.1" 200 897
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2436
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2487
Watching for file changes with StatReloader
Главная страница была посещена.
"GET / HTTP/1.1" 200 903
"GET /static/my_dz_1/css/style.css HTTP/1.1" 200 609
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 1213
Главная страница была посещена.
"GET / HTTP/1.1" 200 903
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 1213
Главная страница была посещена.
"GET / HTTP/1.1" 200 903
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 1213
Главная страница была посещена.
"GET / HTTP/1.1" 200 903
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 894
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 894
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 894
Watching for file changes with StatReloader
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 894
Главная страница была посещена.
"GET / HTTP/1.1" 200 903
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 894
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 894
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 894
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 907
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 907
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 907
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 907
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 907
Главная страница была посещена.
"GET / HTTP/1.1" 200 916
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 907
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 1226
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 1226
Главная страница была посещена.
"GET / HTTP/1.1" 200 916
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 1226
C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_1\views.py changed, reloading.
Watching for file changes with StatReloader
Главная страница была посещена.
"GET / HTTP/1.1" 200 916
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 1226
Главная страница была посещена.
"GET / HTTP/1.1" 200 916
C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_1\views.py changed, reloading.
Watching for file changes with StatReloader
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 918
Главная страница была посещена.
"GET / HTTP/1.1" 200 945
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 1226
Главная страница была посещена.
"GET / HTTP/1.1" 200 945
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 1226
Главная страница была посещена.
"GET / HTTP/1.1" 200 945
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 1226
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 1226
C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_1\views.py changed, reloading.
Watching for file changes with StatReloader
Главная страница была посещена.
"GET / HTTP/1.1" 200 904
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 1226
Главная страница была посещена.
"GET / HTTP/1.1" 200 904
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 1226
Главная страница была посещена.
"GET / HTTP/1.1" 200 904
Главная страница была посещена.
"GET / HTTP/1.1" 200 904
"О себе" страница была посещена.
"GET /about/ HTTP/1.1" 200 1226
Главная страница была посещена.
"GET / HTTP/1.1" 200 904
Watching for file changes with StatReloader
C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_1\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Главная страница была посещена.
"GET / HTTP/1.1" 200 904
C:\Users\it\Desktop\seminar_dz\seminar_dz\seminar_dz\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2436
"GET /client/3/ HTTP/1.1" 200 761
"GET /static/my_dz_2/css/style.css HTTP/1.1" 304 0
"GET /clients/ HTTP/1.1" 200 897
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2436
"GET /client/3/ HTTP/1.1" 200 761
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 10629
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2114
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 10629
"GET / HTTP/1.1" 200 10629
C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2436
Not Found: /
"GET / HTTP/1.1" 404 2436
Internal Server Error: /client/3/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py", line 8, in client_detail
    client = Client.objects.get(pk=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
my_dz_3.models.Client.DoesNotExist: Client matching query does not exist.
"GET /client/3/ HTTP/1.1" 500 72634
Internal Server Error: /client/3/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py", line 8, in client_detail
    client = Client.objects.get(pk=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
my_dz_3.models.Client.DoesNotExist: Client matching query does not exist.
"GET /client/3/ HTTP/1.1" 500 72360
Internal Server Error: /client/3/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py", line 8, in client_detail
    client = Client.objects.get(pk=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
my_dz_3.models.Client.DoesNotExist: Client matching query does not exist.
"GET /client/3/ HTTP/1.1" 500 72634
"GET /clients/ HTTP/1.1" 200 389
C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 389
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /clients/ HTTP/1.1" 200 389
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
Not Found: /clients/2
"GET /clients/2 HTTP/1.1" 404 2481
"GET /clients/ HTTP/1.1" 200 389
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
Internal Server Error: /client/1/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py", line 8, in client_detail
    client = Client.objects.get(pk=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
my_dz_3.models.Client.DoesNotExist: Client matching query does not exist.
"GET /client/1/ HTTP/1.1" 500 72360
Not Found: /
"GET / HTTP/1.1" 404 2436
Internal Server Error: /client/3/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py", line 8, in client_detail
    client = Client.objects.get(pk=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
my_dz_3.models.Client.DoesNotExist: Client matching query does not exist.
"GET /client/3/ HTTP/1.1" 500 72634
Not Found: /client/3/1
"GET /client/3/1 HTTP/1.1" 404 2484
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2436
Internal Server Error: /client/3/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py", line 8, in client_detail
    client = Client.objects.get(pk=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
my_dz_3.models.Client.DoesNotExist: Client matching query does not exist.
"GET /client/3/ HTTP/1.1" 500 72656
Internal Server Error: /client/3/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py", line 8, in client_detail
    client = Client.objects.get(pk=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
my_dz_3.models.Client.DoesNotExist: Client matching query does not exist.
"GET /client/3/ HTTP/1.1" 500 72382
"GET /clients/ HTTP/1.1" 200 595
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
Internal Server Error: /client/1/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py", line 10, in client_detail
    return render(request, 'my_dz_3/client_detail.html', {'client': client, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'client_orders' not found. 'client_orders' is not a valid view function or pattern name.
"GET /client/1/ HTTP/1.1" 500 115217
"GET /clients/ HTTP/1.1" 200 595
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /clients/ HTTP/1.1" 200 595
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 595
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
Internal Server Error: /client/1/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py", line 10, in client_detail
    return render(request, 'my_dz_3/client_detail.html', {'client': client, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'client_orders' not found. 'client_orders' is not a valid view function or pattern name.
"GET /client/1/ HTTP/1.1" 500 115217
C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2641
Internal Server Error: /client/3/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py", line 8, in client_detail
    client = Client.objects.get(pk=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
my_dz_3.models.Client.DoesNotExist: Client matching query does not exist.
"GET /client/3/ HTTP/1.1" 500 72656
Not Found: /client/3/2
"GET /client/3/2 HTTP/1.1" 404 2689
"GET /client/3 HTTP/1.1" 301 0
Internal Server Error: /client/3/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py", line 8, in client_detail
    client = Client.objects.get(pk=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
my_dz_3.models.Client.DoesNotExist: Client matching query does not exist.
"GET /client/3/ HTTP/1.1" 500 72382
Internal Server Error: /client/3/orders/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py", line 17, in client_orders
    client = Client.objects.get(pk=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
my_dz_3.models.Client.DoesNotExist: Client matching query does not exist.
"GET /client/3/orders/ HTTP/1.1" 500 72507
"GET /client/3/orders HTTP/1.1" 301 0
Internal Server Error: /client/3/orders/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py", line 17, in client_orders
    client = Client.objects.get(pk=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
my_dz_3.models.Client.DoesNotExist: Client matching query does not exist.
"GET /client/3/orders/ HTTP/1.1" 500 72507
Not Found: /client/3/1
"GET /client/3/1 HTTP/1.1" 404 2689
C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /client/3/1
"GET /client/3/1 HTTP/1.1" 404 2842
"GET /clients/ HTTP/1.1" 200 595
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /client/2/ HTTP/1.1" 200 805
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /client/1/ HTTP/1.1" 200 906
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /client/1/orders/ HTTP/1.1" 200 950
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /client/1/ HTTP/1.1" 200 906
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /client/1/ HTTP/1.1" 200 906
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /client/1/ HTTP/1.1" 200 906
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /client/2/ HTTP/1.1" 200 805
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /client/2/orders/ HTTP/1.1" 200 854
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /client/1/ HTTP/1.1" 200 906
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
Not Found: /client/1/2
"GET /client/1/2 HTTP/1.1" 404 2842
"GET /client/1/ HTTP/1.1" 200 906
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
Not Found: /client/1/1
"GET /client/1/1 HTTP/1.1" 404 2842
Not Found: /client/1/1/
"GET /client/1/1/ HTTP/1.1" 404 2845
"GET /client/1/orders HTTP/1.1" 301 0
"GET /client/1/orders/ HTTP/1.1" 200 950
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /client/2/orders/ HTTP/1.1" 200 854
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /clients/ HTTP/1.1" 200 595
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /clients/ HTTP/1.1" 200 602
"GET /clients/ HTTP/1.1" 200 602
"GET /clients/ HTTP/1.1" 200 602
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 602
C:\Users\it\Desktop\seminar_dz\seminar_dz\seminar_dz\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 595
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /clients/ HTTP/1.1" 200 595
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /client/1/ HTTP/1.1" 200 906
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /client/1/ HTTP/1.1" 200 906
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /client/1/ HTTP/1.1" 200 906
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /client/1/ HTTP/1.1" 200 906
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /clients/ HTTP/1.1" 200 595
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /client/1/ HTTP/1.1" 200 906
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /client/1/orders/ HTTP/1.1" 200 950
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /client/1/orders/ HTTP/1.1" 200 950
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
"GET /static/my_dz_3/css/style.css HTTP/1.1" 404 1822
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 595
"GET /static/my_dz_3/css/style.css HTTP/1.1" 200 609
"GET /client/1/ HTTP/1.1" 200 906
"GET /client/1/orders/ HTTP/1.1" 200 950
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2794
Internal Server Error: /client/3/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py", line 8, in client_detail
    client = Client.objects.get(pk=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
my_dz_3.models.Client.DoesNotExist: Client matching query does not exist.
"GET /client/3/ HTTP/1.1" 500 72722
Internal Server Error: /client/3/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py", line 8, in client_detail
    client = Client.objects.get(pk=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
my_dz_3.models.Client.DoesNotExist: Client matching query does not exist.
"GET /client/3/ HTTP/1.1" 500 72448
Internal Server Error: /clients/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py", line 15, in client_list
    return render(request, 'my_dz_3/client_list.html', {'clients': clients})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /clients/ HTTP/1.1" 500 126385
Internal Server Error: /clients/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py", line 15, in client_list
    return render(request, 'my_dz_3/client_list.html', {'clients': clients})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /clients/ HTTP/1.1" 500 126111
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 627
"GET /client/1/ HTTP/1.1" 200 844
Watching for file changes with StatReloader
"GET /client/1/ HTTP/1.1" 200 844
"GET /client/1/ HTTP/1.1" 200 844
Not Found: /clientы
"GET /client%D1%8B HTTP/1.1" 404 2840
"GET /clients/ HTTP/1.1" 200 627
"GET /client/1/ HTTP/1.1" 200 844
"GET /client/2/ HTTP/1.1" 200 753
"GET /client/1/ HTTP/1.1" 200 844
"GET /client/1/orders/ HTTP/1.1" 200 907
Watching for file changes with StatReloader
Internal Server Error: /client/1/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py", line 10, in client_detail
    return render(request, 'my_dz_3/client_detail.html', {'client': client, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 565, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 32: 'endblock'. Did you forget to register or load this tag?
"GET /client/1/ HTTP/1.1" 500 140301
"GET /clients/ HTTP/1.1" 200 627
Internal Server Error: /client/1/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py", line 10, in client_detail
    return render(request, 'my_dz_3/client_detail.html', {'client': client, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 565, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 32: 'endblock'. Did you forget to register or load this tag?
"GET /client/1/ HTTP/1.1" 500 140164
"GET /client/1/ HTTP/1.1" 200 844
Watching for file changes with StatReloader
Internal Server Error: /client/1/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py", line 10, in client_detail
    return render(request, 'my_dz_3/client_detail.html', {'client': client, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'client_order_products' not found. 'client_order_products' is not a valid view function or pattern name.
"GET /client/1/ HTTP/1.1" 500 161851
Internal Server Error: /client/1/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py", line 10, in client_detail
    return render(request, 'my_dz_3/client_detail.html', {'client': client, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'client_order_products' not found. 'client_order_products' is not a valid view function or pattern name.
"GET /client/1/ HTTP/1.1" 500 161714
"GET /clients/ HTTP/1.1" 200 627
Internal Server Error: /client/1/
Traceback (most recent call last):
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py", line 10, in client_detail
    return render(request, 'my_dz_3/client_detail.html', {'client': client, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\it\Desktop\seminar_dz\.venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'client_order_products' not found. 'client_order_products' is not a valid view function or pattern name.
"GET /client/1/ HTTP/1.1" 500 161873
C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /client/1/ HTTP/1.1" 200 844
"GET /client/1/orders/ HTTP/1.1" 200 907
Not Found: /client/12orders/
"GET /client/12orders/ HTTP/1.1" 404 2860
"GET /client/2/orders/ HTTP/1.1" 200 835
"GET /clients/ HTTP/1.1" 200 627
"GET /client/2/ HTTP/1.1" 200 753
"GET /client/1/ HTTP/1.1" 200 844
"GET /client/1/ HTTP/1.1" 200 844
"GET /client/1/ HTTP/1.1" 200 844
"GET /client/2/ HTTP/1.1" 200 753
Not Found: /client/2/orler
"GET /client/2/orler HTTP/1.1" 404 2854
Not Found: /client/2/orlers
"GET /client/2/orlers HTTP/1.1" 404 2857
"GET /client/2/orders HTTP/1.1" 301 0
"GET /client/2/orders/ HTTP/1.1" 200 835
"GET /clients/ HTTP/1.1" 200 627
"GET /client/1/ HTTP/1.1" 200 844
Watching for file changes with StatReloader
"GET /client/1/ HTTP/1.1" 200 844
"GET /client/1/ HTTP/1.1" 200 844
"GET /client/2/ HTTP/1.1" 200 753
"GET /clients/ HTTP/1.1" 200 767
"GET /client/1/ HTTP/1.1" 200 844
"GET /client/2/orders/ HTTP/1.1" 200 835
"GET /clients/ HTTP/1.1" 200 645
"GET /client/1/ HTTP/1.1" 200 844
"GET /client/2/ HTTP/1.1" 200 753
Watching for file changes with StatReloader
"GET /client/2/ HTTP/1.1" 200 753
"GET /clients/ HTTP/1.1" 200 722
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 722
"GET /clients/ HTTP/1.1" 200 722
Not Found: /clients/1
"GET /clients/1 HTTP/1.1" 404 2839
"GET /client/1/ HTTP/1.1" 200 844
"GET /clients/ HTTP/1.1" 200 722
"GET /clients/ HTTP/1.1" 200 630
"GET /client/1/ HTTP/1.1" 200 844
"GET /client/1/ HTTP/1.1" 200 844
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 630
"GET /client/1/ HTTP/1.1" 200 1018
"GET /client/2/ HTTP/1.1" 200 753
"GET /client/2/orders/ HTTP/1.1" 200 835
Watching for file changes with StatReloader
"GET /client/1/ HTTP/1.1" 200 1239
"GET /client/1/orders/ HTTP/1.1" 200 907
"GET /client/1/orders/ HTTP/1.1" 200 907
"GET /client/1/orders/ HTTP/1.1" 200 907
"GET /client/2/ HTTP/1.1" 200 812
"GET /client/2/orders/ HTTP/1.1" 200 835
"GET /client/2/ HTTP/1.1" 200 812
"GET / HTTP/1.1" 200 630
"GET /client/2/ HTTP/1.1" 200 812
"GET /client/2/orders/ HTTP/1.1" 200 835
"GET /client/1/ HTTP/1.1" 200 1239
"GET /client/1/orders/ HTTP/1.1" 200 907
"GET /client/1/orders/ HTTP/1.1" 200 907
"GET /client/1/orders/ HTTP/1.1" 200 907
Watching for file changes with StatReloader
"GET /client/1/orders/ HTTP/1.1" 200 924
"GET /client/1/orders/ HTTP/1.1" 200 919
"GET /client/1/orders/ HTTP/1.1" 200 921
"GET /client/1/orders/ HTTP/1.1" 200 921
"GET /client/2/ HTTP/1.1" 200 812
"GET /client/2/orders/ HTTP/1.1" 200 847
"GET /client/2/ HTTP/1.1" 200 891
"GET /static/my_dz_3/images/your_image.jpg HTTP/1.1" 404 1846
"GET / HTTP/1.1" 200 709
"GET /static/my_dz_3/images/your_image.jpg HTTP/1.1" 404 1846
"GET / HTTP/1.1" 200 701
"GET /static/my_dz_3/image/583.jpg HTTP/1.1" 200 2057688
"GET / HTTP/1.1" 200 732
"GET /static/my_dz_3/images/your_image.jpg HTTP/1.1" 404 1846
"GET / HTTP/1.1" 200 724
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 724
"GET / HTTP/1.1" 200 724
"GET / HTTP/1.1" 200 724
"GET / HTTP/1.1" 200 724
"GET / HTTP/1.1" 200 735
"GET /static/my_dz_3/images/your_image.jpg HTTP/1.1" 404 1846
"GET / HTTP/1.1" 200 727
"GET /client/1/ HTTP/1.1" 200 1336
"GET /client/1/ HTTP/1.1" 200 1564
"GET / HTTP/1.1" 200 955
"GET /client/1/ HTTP/1.1" 200 1690
"GET /client/1/ HTTP/1.1" 200 1690
"GET /client/1/orders/ HTTP/1.1" 200 1372
"GET /client/1/orders/ HTTP/1.1" 200 974
"GET /client/1/ HTTP/1.1" 200 1292
"GET /client/1/ HTTP/1.1" 200 1690
Watching for file changes with StatReloader
"GET /client/1/ HTTP/1.1" 200 1690
"GET / HTTP/1.1" 200 1164
"GET /client/3/ HTTP/1.1" 200 1409
"GET /client/3/orders/ HTTP/1.1" 200 1232
"GET /client/1/ HTTP/1.1" 200 1690
"GET /client/1/orders/ HTTP/1.1" 200 1372
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1166
"GET /client/1/ HTTP/1.1" 200 1687
"GET /client/1/orders/ HTTP/1.1" 200 1512
Watching for file changes with StatReloader
"GET /client/1/orders/ HTTP/1.1" 200 1512
"GET /client/1/orders/ HTTP/1.1" 200 1512
"GET /client/1/orders/ HTTP/1.1" 200 1512
"GET /client/1/orders/ HTTP/1.1" 200 1512
"GET /client/1/orders/ HTTP/1.1" 200 1512
"GET /client/1/orders/ HTTP/1.1" 200 1512
Watching for file changes with StatReloader
"GET /client/1/orders/ HTTP/1.1" 200 1512
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1166
"GET /client/1/ HTTP/1.1" 200 1971
"GET /client/1/orders/ HTTP/1.1" 200 1516
"GET /client/1/orders/ HTTP/1.1" 200 1492
"GET /client/1/orders/ HTTP/1.1" 200 1492
"GET /client/1/orders/ HTTP/1.1" 200 1492
Watching for file changes with StatReloader
"GET /client/1/orders/ HTTP/1.1" 200 1489
"GET /client/1/orders/ HTTP/1.1" 200 1510
Watching for file changes with StatReloader
"GET /client/1/orders/ HTTP/1.1" 200 1510
"GET /client/1/orders/ HTTP/1.1" 200 1510
"GET /client/1/orders/ HTTP/1.1" 200 1510
"GET /client/1/orders/ HTTP/1.1" 200 1510
"GET /client/1/orders/ HTTP/1.1" 200 1575
"GET /client/1/orders/ HTTP/1.1" 200 1560
C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /client/1/orders/ HTTP/1.1" 200 1560
"GET /client/1/orders/ HTTP/1.1" 200 1560
"GET /client/1/orders/ HTTP/1.1" 200 1560
C:\Users\it\Desktop\seminar_dz\seminar_dz\my_dz_3\views.py changed, reloading.
Watching for file changes with StatReloader
